name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Koyeb Docker Registry
        run: docker login -u abishanavanee0207@gmail.com -p ${{ secrets.KOYEB_API_TOKEN }} registry.koyeb.com

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t registry.koyeb.com/fluttering-minetta/abisha-movie-buzz:latest .
          docker push registry.koyeb.com/fluttering-minetta/abisha-movie-buzz:latest

      - name: Deploy to Koyeb
        run: |
          curl -X POST https://app.koyeb.com/v1/apps/fluttering-minetta/abisha-movie-buzz/deploy \
          -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}"
